fieldLayouts:
  4e002902-59ed-4470-be61-917fe2bb0c36:
    tabs:
      -
        elements:
          -
            fieldUid: 768270aa-bec7-4235-a7d0-589707ca497e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d77f339-131b-40ea-a446-d163ee0d4945
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c95fe0cd-27df-4250-984c-a1e06f474e61
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: abb156ae-844b-4f1a-a1b4-63ce080a0009
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Globals
        sortOrder: 1
handle: hopscotch
name: Hopscotch
