fieldLayouts:
  a340e503-e7bf-4ec2-8a7d-e161ac6dfe0e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homeBanner
hasUrls: true
name: 'Home Banner'
settings:
  path: '@mediaBasePath/home/banner'
sortOrder: 1
type: craft\volumes\Local
url: '@mediaBaseUrl/home/banner'
