enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  fb7efba8-b557-46fd-82c6-4e761b57c79b:
    enabledByDefault: true
    hasUrls: true
    template: templates/about
    uriFormat: about
type: single
