field: e7b3b7f1-8c18-4496-999a-dfe188acd0a3
fieldLayouts:
  141a4b76-7277-4162-87e7-403db8715cf0:
    tabs:
      -
        elements:
          -
            fieldUid: 81db9add-1ad6-416e-a57f-950d6abedb87
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 91450004-2ff4-4d87-852d-fd3e1cf152fc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  81db9add-1ad6-416e-a57f-950d6abedb87:
    contentColumnType: text
    fieldGroup: null
    handle: faqSectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  91450004-2ff4-4d87-852d-fd3e1cf152fc:
    contentColumnType: text
    fieldGroup: null
    handle: faq
    instructions: ''
    name: FAQ
    searchable: false
    settings:
      addRowLabel: 'Add a FAQ'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Question
                -
                  - handle
                  - question
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Answer
                -
                  - handle
                  - answer
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: faqSection
name: 'FAQ Section'
sortOrder: 1
