field: 0fc9f5ae-aaad-4887-95e9-e411421a5beb
fieldLayouts:
  40dfecf4-ec01-414b-9bc9-33b6b105f381:
    tabs:
      -
        elements:
          -
            fieldUid: 7c112a51-be84-4da5-a2d8-b31e643054e4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55ff5573-459b-4b61-a211-3226dd0a25a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0d79509-418a-4458-98dd-98c8fafaffa9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  55ff5573-459b-4b61-a211-3226dd0a25a9:
    contentColumnType: text
    fieldGroup: null
    handle: guidelineHeader
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7c112a51-be84-4da5-a2d8-b31e643054e4:
    contentColumnType: string
    fieldGroup: null
    handle: numberGrpahic
    instructions: 'Graphic size: 150 x 150'
    name: 'Number Grpahic'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:28998fcf-08b5-42e2-99bf-32b99d7e71df'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:22d4c992-dba7-449e-b36d-ac36420f47e5'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:97d6d9f3-1a93-443a-bfa5-69cdc7328c00'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a0d79509-418a-4458-98dd-98c8fafaffa9:
    contentColumnType: text
    fieldGroup: null
    handle: guidelineContent
    instructions: ''
    name: 'Guideline Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: guideline
name: Guideline
sortOrder: 1
