contentColumnType: text
fieldGroup: d728ed2f-7f94-45a3-ba4c-04c8f011c931
handle: covidBottomParagraph
instructions: ''
name: 'Covid Bottom Paragraph'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
