contentColumnType: text
fieldGroup: 5a732bb2-b780-4b03-8e60-569879bbaa22
handle: covidResponse
instructions: ''
name: 'Covid Response'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  configSelectionMode: manual
  defaultTransform: ''
  manualConfig: "{\r\n  \"buttons\": [\"link\"]\r\n}"
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
