contentColumnType: string(255)
fieldGroup: dc84b6d1-777b-4368-ae5b-41cb8bcfbe59
handle: getTicketsLink
instructions: ''
name: 'Get Tickets Link'
searchable: false
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
