contentColumnType: text
fieldGroup: 5a732bb2-b780-4b03-8e60-569879bbaa22
handle: hoursDescription
instructions: 'Paragraph inside ''Hours'' box'
name: 'Hours Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
